In [123]:
import numpy as np

In [124]:
a=[1,2,3,4]
b=[5,6,7,8]


In [125]:
[a[i] + b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [126]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [127]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
arr[1:3]  ##start_row:end_row,start_col:end_column

array([[4, 5, 6],
       [7, 8, 9]])

In [129]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [130]:
arr[2:,:1]

array([[7]])

In [131]:
arr[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [132]:
arr[:,2:]

array([[3],
       [6],
       [9]])

In [133]:
arr[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [134]:
arr[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [135]:
arr[:,1:2]

array([[2],
       [5],
       [8]])

In [136]:
arr[1:2,:]

array([[4, 5, 6]])

In [137]:
arr[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [139]:
arr[:2,1:2]

array([[2],
       [5]])

In [140]:
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
arr[0:3,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [143]:
arr[1:2:,1:2]

array([[5]])

In [144]:
arr[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [145]:
arr[1:,::2]

array([[4, 6],
       [7, 9]])

In [146]:
a=[1,2,3,4,5]

In [147]:
a[1:2]

[2]

In [148]:
np.eye(3,3).astype("int32").dtype

dtype('int32')

In [149]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [150]:
a=np.arange(10,50,3)

In [151]:
a

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [152]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [153]:
###vector operation

In [154]:
a=np.array([1,2,3])
a**2

array([1, 4, 9])

In [155]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[4, 5],
        [6, 7]]))

In [156]:
np.dot(a,b)

array([[16, 19],
       [36, 43]])

In [157]:
a.T

array([[1, 3],
       [2, 4]])

In [158]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [159]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [160]:
np.linalg.det(a)


np.float64(0.0)

In [161]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])


In [162]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [163]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [164]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [165]:
a=np.array([1,2,3,4,5,6,7,8,9,10,4,1])

In [166]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [167]:
np.reshape(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1]])

In [168]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [169]:
np.resize(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1]])

In [170]:
np.resize(a,(4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1],
       [ 1,  2,  3,  4]])

In [171]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10,  4,  1])]

In [172]:
n=np.array([1,2,3,4,5,6,7])

In [173]:
n

array([1, 2, 3, 4, 5, 6, 7])

In [174]:
##copy and views

In [175]:
arr=np.array([1,2,3,4,5,6])

In [176]:
b=arr.view()

In [177]:
b[0]=10

In [178]:
arr,a

(array([10,  2,  3,  4,  5,  6]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1]))

In [179]:
arr,b

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [180]:
c=arr.copy()

In [181]:
arr,c

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [182]:
c[0]=11

In [183]:
arr,c

(array([10,  2,  3,  4,  5,  6]), array([11,  2,  3,  4,  5,  6]))

In [184]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
np.sum(a,axis=0)

array([12, 15, 18])

In [186]:
def mean(array):
    n=len(array)
    return np.sum(array)/n

In [187]:
mean(np.array([1,2,3,4,5,6]))

np.float64(3.5)

In [188]:
def variance(array):
    n=len(array)
    m=mean(array)
    return np.sum((array - m)**2)/n

In [189]:
variance(np.array([1,2,3,4,5,6]))

np.float64(2.9166666666666665)

In [1]:
import numpy as np
scores = np.random.randint(50, 101, size=(5, 3))
mean_scores = scores.mean(axis=0)
centered_scores = scores - mean_scores
print("Original Scores (5 students x 3 subjects):")
print(scores)

print("\nMean Score of Each Subject:")
print(mean_scores)

print("\nCentered Scores (After Normalization):")
print(centered_scores)


Original Scores (5 students x 3 subjects):
[[ 75  98  92]
 [ 75  99  50]
 [ 64  88  80]
 [100  97  90]
 [ 60  80  51]]

Mean Score of Each Subject:
[74.8 92.4 72.6]

Centered Scores (After Normalization):
[[  0.2   5.6  19.4]
 [  0.2   6.6 -22.6]
 [-10.8  -4.4   7.4]
 [ 25.2   4.6  17.4]
 [-14.8 -12.4 -21.6]]


In [2]:
import numpy as np
data = np.arange(24)
reshaped_data = data.reshape(4, 3, 2)
final_data = reshaped_data.transpose(0, 2, 1)
print("Final Shape:", final_data.shape)
print("\nFinal Array:")
print(final_data)


Final Shape: (4, 2, 3)

Final Array:
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]
